// <auto-generated />
using System;
using AggregatorService.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AggregatorService.ApiService.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260208181523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AggregatorService.ApiService.Domain.Models.Candle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Period")
                        .HasColumnType("interval");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Volatility")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Period", "OpenTime");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("AggregatorService.ApiService.Domain.Models.Instrument", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Symbol");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Symbol = "BTCUSD",
                            BaseCurrency = "BTC",
                            IsActive = true,
                            QuoteCurrency = "USD",
                            Type = "Crypto"
                        },
                        new
                        {
                            Symbol = "ETHUSD",
                            BaseCurrency = "ETH",
                            IsActive = true,
                            QuoteCurrency = "USD",
                            Type = "Crypto"
                        },
                        new
                        {
                            Symbol = "SOLUSD",
                            BaseCurrency = "SOL",
                            IsActive = true,
                            QuoteCurrency = "USD",
                            Type = "Crypto"
                        });
                });

            modelBuilder.Entity("AggregatorService.ApiService.Domain.Models.SourceStatus", b =>
                {
                    b.Property<string>("SourceName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TicksCount")
                        .HasColumnType("bigint");

                    b.HasKey("SourceName");

                    b.ToTable("SourceStatuses");
                });

            modelBuilder.Entity("AggregatorService.ApiService.Domain.Models.Tick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp");

                    b.ToTable("Ticks");
                });
#pragma warning restore 612, 618
        }
    }
}
